### PR TITLE
Refactored code to ES6 syntax

### LINKED ISSUE #9: Refactor code to align to ES6 syntax

### PR DESCRIPTION
**Pull request by burhanharoon**
Allthough, there wasnt much to refactor, but I did my best. 
This PR is related to this [issue](https://github.com/Kunalbhandari/portfolio/issues/9)

### CODE REVIEW

**Review by Kunalbhandari — APPROVED** [review]

**Comment by Kunalbhandari** [comment]
before i merge could you just share screen shots of this run from your branch fro both /home and /experiences route
@burhanharoon

**Comment by burhanharoon** [comment]
/home 
image

/experience
image

**Comment by Kunalbhandari** [comment]
can that tongue twister <> be placed rightly
http://www.kunalbhandari.com/

check this domain URL

**Comment by burhanharoon** [comment]
This domain is not working

**Comment by Kunalbhandari** [comment]
http://kunalbhandari.com

try with http and not https

**Comment by Kunalbhandari** [comment]
can you do the required changes before i merge this PR ?

**Comment by burhanharoon** [comment]
> Author

I can do the changes, but this is looking much better than the new deisgn.

**Comment by burhanharoon** [comment]
Pushed the quote changes! Please have a look!

**Pull request merged**
